"use strict";
exports.__esModule = true;
var num1 = 3;
var num2 = 5;
var num3 = 6;
var num4 = 8;
var num5 = 13;
console.log(num1);
console.log(num2);
console.log(num3);
console.log(num4);
console.log(num5);
